[package]
name = "strinxs"
version = "0.1.3"
authors = ["Patrick Amrein <amrein@ubique.ch>"]
edition = "2018"

[dependencies]
leb128 = "*"
regex = "1"
zip = "0.5"
chrono = { version = "0.4", features = ["serde"] }